# https://github.com/wphillipmoore/standard-actions/blob/develop/.github/workflows/README.md
name: CD

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

permissions:
  attestations: write
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    uses: wphillipmoore/standard-actions/.github/workflows/cd-release.yml@v1.5
    with:
      language: python
      container-tag: "3.14"
    secrets: inherit
